---
title: "Portfolio"
---

# [Wildfires at LavaBeds National Monument](portfolio_pages/LABE.qmd)

# [Phenological machine learning in Wetlands](phenoML.quarto)

# [Performing object extraction on historic aerial photos](portfolio_pages/historicOBIA.qmd)

# [The impacts of rainfall on land ownership: A Bayesian approach](portfolio_pages/AgOwnership.qmd)

The adverse effects of climate change are likely to harm food supplies and agricultural livelihoods worldwide. Faced with challenges resulting from increasingly unpredictable weather patterns, some farmers might be forced abandon their occupation. A dramatic increase in landless population could result in increased levels of social and political conflict. After analyzing agriculture and precipitation data from a large number of countries worldwide, we found that drier than average growing season weather is associated with declining landownership rates. For every consecutive dry growing season before a land ownership survey, the agricultural land ownership rate of the affected region falls by 2.51%. This article is an attempt to describe the process behind that analysis.